add online man

diff --git a/scripts/aliases b/scripts/aliases
--- a/scripts/aliases
+++ b/scripts/aliases
@@ -82,6 +82,23 @@ function __sudo() {
     fi
 }
 
+function __man() {
+    if command man "$1" &>/dev/null; then
+        command man "$1"
+    else
+        local url="https://dyn.manpages.debian.org/bookworm/debian-goodies/${1}.1.en.gz"
+        local http_code
+        if ! http_code=$(curl -s -o /dev/null -w "%{http_code}" "$url"); then
+            echo "Error fetching page"
+        elif [ "$http_code" -eq 404 ]; then
+            command man "$1"
+        else
+            curl -s "$url" | command man -l
+        fi
+    fi
+}
+
+
 alias cat="bat"
 alias l="ls -lhA "
 alias ls="ls --color=auto "
@@ -108,3 +125,4 @@ alias nrs="npm run serve"
 
 alias p="__package_management "
 alias sudo="__sudo"
+alias man="__man"
